/*
    name matches category field in all.json
    ignored all honorary awards and stuff pre 1950
    added category to normalize discrepancies between years
*/

export type AwardCategory = (typeof awardsMap)[number]['category'];
export type AwardName = (typeof awardsMap)[number]['name'];

// prettier-ignore
export const awardsMap = [
  { name: 'ACTOR', category: 'actor' },
  { name: 'ACTOR IN A LEADING ROLE', category: 'actor' },
  { name: 'ACTOR IN A SUPPORTING ROLE', category: 'supporting_actor' },
  { name: 'ACTRESS', category: 'actress' },
  { name: 'ACTRESS IN A LEADING ROLE', category: 'actress' },
  { name: 'ACTRESS IN A SUPPORTING ROLE', category: 'supporting_actress' },
  { name: 'ANIMATED FEATURE FILM', category: 'animated_film' },
  { name: 'ART DIRECTION', category: 'art_direction' },
  { name: 'ART DIRECTION (Black-and-White)', category: 'art_direction' },
  { name: 'ART DIRECTION (Color)', category: 'art_direction' },
  { name: 'BEST MOTION PICTURE', category: 'best_picture' },
  { name: 'BEST PICTURE', category: 'best_picture' },
  { name: 'CINEMATOGRAPHY', category: 'cinematography' },
  { name: 'CINEMATOGRAPHY (Black-and-White)', category: 'cinematography' },
  { name: 'CINEMATOGRAPHY (Color)', category: 'cinematography' },
  { name: 'COSTUME DESIGN', category: 'costume' },
  { name: 'COSTUME DESIGN (Black-and-White)', category: 'costume' },
  { name: 'COSTUME DESIGN (Color)', category: 'costume' },
  { name: 'DIRECTING', category: 'directing' },
  { name: 'DOCUMENTARY (Feature)', category: 'documentary' },
  { name: 'DOCUMENTARY (Short Subject)', category: 'documentary_short' },
  { name: 'DOCUMENTARY FEATURE FILM', category: 'documentary' },
  { name: 'DOCUMENTARY SHORT FILM', category: 'documentary_short' },
  { name: 'FILM EDITING', category: 'editing' },
  { name: 'FOREIGN LANGUAGE FILM', category: 'foreign_language' },
  { name: 'INTERNATIONAL FEATURE FILM', category: 'foreign_language' },
  { name: 'MAKEUP', category: 'makeup' },
  { name: 'MAKEUP AND HAIRSTYLING', category: 'makeup' },
  { name: 'MUSIC (Adaptation Score)', category: 'music' },
  { name: 'MUSIC (Music Score of a Dramatic or Comedy Picture)', category: 'music' },
  { name: 'MUSIC (Music Score--substantially original)', category: 'music' },
  { name: 'MUSIC (Original Dramatic Score)', category: 'music' },
  { name: 'MUSIC (Original Music Score)', category: 'music' },
  { name: 'MUSIC (Original Musical or Comedy Score)', category: 'music' },
  { name: 'MUSIC (Original Score)', category: 'music' },
  { name: 'MUSIC (Original Score--for a motion picture [not a musical])', category: 'music' },
  { name: 'MUSIC (Original Song Score and Its Adaptation -or- Adaptation Score)', category: 'music' },
  { name: 'MUSIC (Original Song Score and Its Adaptation or Adaptation Score)', category: 'music' },
  { name: 'MUSIC (Original Song Score or Adaptation Score)', category: 'music' },
  { name: 'MUSIC (Original Song Score)', category: 'song' },
  { name: 'MUSIC (Original Song)', category: 'song' },
  { name: 'MUSIC (Score of a Musical Picture--original or adaptation)', category: 'music' },
  { name: 'MUSIC (Scoring of Music--adaptation or treatment)', category: 'music' },
  { name: 'MUSIC (Scoring of a Musical Picture)', category: 'music' },
  { name: 'MUSIC (Scoring)', category: 'music' },
  { name: 'MUSIC (Scoring: Adaptation and Original Song Score)', category: 'song' },
  { name: 'MUSIC (Scoring: Original Song Score and Adaptation -or- Scoring: Adaptation)', category: 'song' },
  { name: 'MUSIC (Song)', category: 'song' },
  { name: 'MUSIC (Song--Original for the Picture)', category: 'song' },
  { name: 'PRODUCTION DESIGN', category: 'production_design' },
  { name: 'SHORT FILM (Animated)', category: 'short' },
  { name: 'SHORT FILM (Dramatic Live Action)', category: 'short' },
  { name: 'SHORT FILM (Live Action)', category: 'short' },
  { name: 'SHORT SUBJECT (Animated)', category: 'short' },
  { name: 'SHORT SUBJECT (Cartoon)', category: 'short' },
  { name: 'SHORT SUBJECT (Live Action)', category: 'short' },
  { name: 'SHORT SUBJECT (One-reel)', category: 'short' },
  { name: 'SHORT SUBJECT (Two-reel)', category: 'short' },
  { name: 'SOUND', category: 'sound' },
  { name: 'SOUND EDITING', category: 'sound' },
  { name: 'SOUND EFFECTS', category: 'sound' },
  { name: 'SOUND EFFECTS EDITING', category: 'sound' },
  { name: 'SOUND MIXING', category: 'sound' },
  { name: 'SOUND RECORDING', category: 'sound' },
  { name: 'SPECIAL ACHIEVEMENT AWARD (Sound Editing)', category: 'sound' },
  { name: 'SPECIAL ACHIEVEMENT AWARD (Sound Effects Editing)', category: 'sound' },
  { name: 'SPECIAL ACHIEVEMENT AWARD (Sound Effects)', category: 'sound' },
  { name: 'SPECIAL ACHIEVEMENT AWARD (Visual Effects)', category: 'visual_effects' },
  { name: 'SPECIAL EFFECTS', category: 'visual_effects' },
  { name: 'SPECIAL VISUAL EFFECTS', category: 'visual_effects' },
  { name: 'VISUAL EFFECTS', category: 'visual_effects' },
  { name: 'WRITING (Adapted Screenplay)', category: 'writing_adapted' },
  { name: 'WRITING (Motion Picture Story)', category: 'writing' },
  { name: 'WRITING (Original Screenplay)', category: 'writing' },
  { name: 'WRITING (Screenplay Adapted from Other Material)', category: 'writing_adapted' },
  { name: 'WRITING (Screenplay Based on Material Previously Produced or Published)', category: 'writing_adapted' },
  { name: 'WRITING (Screenplay Based on Material from Another Medium)', category: 'writing_adapted' },
  { name: 'WRITING (Screenplay Written Directly for the Screen)', category: 'writing' },
  { name: 'WRITING (Screenplay Written Directly for the Screen--based on factual material or on story material not previously published or produced)', category: 'writing' },
  { name: 'WRITING (Screenplay)', category: 'writing' },
  { name: 'WRITING (Screenplay--Adapted)', category: 'writing_adapted' },
  { name: 'WRITING (Screenplay--Original)', category: 'writing' },
  { name: 'WRITING (Screenplay--based on material from another medium)', category: 'writing_adapted' },
  { name: 'WRITING (Story and Screenplay)', category: 'writing' },
  { name: 'WRITING (Story and Screenplay--based on factual material or material not previously published or produced)', category: 'writing' },
  { name: 'WRITING (Story and Screenplay--based on material not previously published or produced)', category: 'writing' },
  { name: 'WRITING (Story and Screenplay--written directly for the screen)', category: 'writing' },
] as const;
