export const categories = [
  { name: 'actor', relevance: 'high' },
  { name: 'actress', relevance: 'high' },
  { name: 'animated_film', relevance: 'medium' },
  { name: 'art_direction', relevance: 'medium' },
  { name: 'best_picture', relevance: 'high' },
  { name: 'cinematography', relevance: 'high' },
  { name: 'costume', relevance: 'medium' },
  { name: 'directing', relevance: 'high' },
  { name: 'documentary', relevance: 'low' },
  { name: 'documentary_short', relevance: 'low' },
  { name: 'editing', relevance: 'medium' },
  { name: 'foreign_language', relevance: 'low' },
  { name: 'makeup', relevance: 'medium' },
  { name: 'music', relevance: 'medium' },
  { name: 'production_design', relevance: 'medium' },
  { name: 'short', relevance: 'low' },
  { name: 'song', relevance: 'low' },
  { name: 'sound', relevance: 'medium' },
  { name: 'supporting_actor', relevance: 'high' },
  { name: 'supporting_actress', relevance: 'high' },
  { name: 'visual_effects', relevance: 'medium' },
  { name: 'writing', relevance: 'high' },
  { name: 'writing_adapted', relevance: 'high' },
];
