import { z } from 'zod';

export const hosts = z.enum([
  'Bill Simmons',
  'Mallory Rubin',
  'Van Lathan',
  'Logan Murdock',
  'Chris Ryan',
  'Sean Fennessey',
  'Juliet Litman',
  'Amanda Dobbins',
  'Ryen Russillo',
  'Craig Horlbeck',
  'Kyle Brandt',
  'Wesley Morris',
  'Danny Kelly',
  'Danny Heifetz',
  'Jodi Walker',
  'Kate Halliwell',
  'Brian Koppelman',
  'Shea Serrano',
  'Wosny Lambre',
  'David Jacoby',
  'Cousin Sal',
  'Gus Ramsey',
  'Charles Holmes',
  'K. Austin Collins',
  'Jimmy Kimmel',
  'Andy Greenwald',
  'Mina Kimes',
  'Chuck Klosterman',
  'Bill Hader',
  'Bill Lawrence',
  'Liz Kelly',
  'Judd Apatow',
  'Jason Concepcion',
  'Issa Rae',
  'Jemele Hill',
  'Quentin Tarantino',
  'The Safdie Brothers',
  'Kari Simmons',
  'Rembert Browne',
  'Bill’s Dad',
  'Aaron Sorkin',
  'Andrew Gruttadaro',
  'Micah Peters',
  'David Shoemaker',
  'Bryan Curtis',
  'Justin Charity',
  'Lindsay Zoladz',
  'Donnie Kwak',
  'Hannah Giorgis',
  'Mark Titus',
  'Dave Chang',
  'Jennifer Lawrence',
  'Zach Baron',
  'Joe House',
]).enum;
