import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDollarSign,
  CircleEqual,
  Clapperboard,
  Clock,
  ExternalLink,
  Film,
  Frown,
  HeartCrack,
  KeyRound,
  Loader2,
  Meh,
  Mic,
  Pencil,
  Piano,
  Popcorn,
  RectangleVertical,
  SlidersHorizontal,
  Star,
  StarHalf,
  Table,
  Trophy,
  Tv,
  User2,
  Video,
  WholeWord,
  XCircle,
} from 'lucide-react';
import { type ComponentPropsWithoutRef } from 'react';

type IconProps = ComponentPropsWithoutRef<typeof ArrowDown>;
export type IconKey = keyof typeof Icon;

export const ConditionalCaret = ({ showing, ...rest }: IconProps & { showing: boolean }) =>
  showing ? <ChevronUp {...rest} /> : <ChevronDown {...rest} />;

export const Icon = {
  Actor: User2,
  ArrowDown: ArrowDown,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  ArrowUp: ArrowUp,
  Calendar: CalendarDays,
  Card: RectangleVertical,
  CaretDown: ChevronDown,
  CaretUp: ChevronUp,
  CaretLeft: ChevronLeft,
  CaretRight: ChevronRight,
  Check,
  Clock: Clock,
  Close: XCircle,
  Dollar: CircleDollarSign,
  FaceFrown: Frown,
  FaceMeh: Meh,
  Filter: CircleEqual,
  FilterSlider: SlidersHorizontal,
  FilmStrip: Film,
  HeartBreak: HeartCrack,
  Key: KeyRound,
  Link: ExternalLink,
  Loading: Loader2,
  Mic: Mic,
  Movie: Clapperboard,
  Piano,
  Pen: Pencil,
  Popcorn: Popcorn,
  Star: Star,
  StarHalf: StarHalf,
  Table: Table,
  Trophy,
  Tv: Tv,
  Video: Video,
  Word: WholeWord,
};
